server:
  port: 8081

spring:
  application:
    name: dynamodb
  cloud:
    vault:
      kv:
        enabled: true
      authentication: TOKEN
      token: spring-boot-dynamodb-token
      scheme: http
      host: localhost
      port: 8200
  config:
    import: vault://

dynamodb:
  endpoint: "dynamodb.eu-central-1.amazonaws.com"
  region: "eu-central-1"
