apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-dynamodb
  labels:
    app: spring-boot-dynamodb
spec:
  replicas: 3
  template:
    metadata:
      name: spring-boot-dynamodb
      labels:
        app: spring-boot-dynamodb
    spec:
      containers:
        - name: spring-boot-dynamodb
          image: milanobrenovic/spring-boot-dynamodb-demo:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: spring-boot-dynamodb
