apiVersion: v1
kind: Service
metadata:
  name: spring-boot-dynamodb
spec:
  selector:
    app: spring-boot-dynamodb
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
