package com.example.dynamodb.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
@DynamoDBTable(tableName = "person")
public class Person {

    @DynamoDBHashKey(attributeName = "person_id")
    @DynamoDBAutoGeneratedKey
    @JsonProperty("person_id")
    private String personId;

    @DynamoDBAttribute(attributeName = "first_name")
    @JsonProperty("first_name")
    private String firstName;

    @DynamoDBAttribute(attributeName = "last_name")
    @JsonProperty("last_name")
    private String lastName;

    @DynamoDBAttribute(attributeName = "email")
    @JsonProperty("email")
    private String email;

    @DynamoDBAttribute(attributeName = "address")
    @JsonProperty("address")
    private Address address;

}
